# fly.toml app configuration file generated for test-jupiter-swap-api on 2023-12-04T14:14:21+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "./jupiter-swap-api"
primary_region = "sin"

[build]
image = "ghcr.io/jup-ag/jupiter-swap-api:latest"

[deploy]
strategy = "bluegreen"

[env]
PORT = "8080"
RPC_URL = "https://virulent-neat-uranium.solana-mainnet.quiknode.pro/34c341f57c26494a7a3422a6a42291e9e6589be5"
YELLOWSTONE_GRPC_ENDPOINT = "https://basic.grpc.solanavibestation.com" # Optional 
YELLOWSTONE_GRPC_X_TOKEN = "f1472ab97472ff4769418168d9f192f0"

[http_service]
force_https = true
internal_port = 8080
auto_stop_machines = true
auto_start_machines = true
min_machines_running = 1
[http_service.concurrency]
type = "requests"
hard_limit = 30
soft_limit = 10

[[http_service.checks]]
interval = "30s"
timeout = "5s"
grace_period = "60s"
method = "GET"
path = "/program-id-to-label"

[[vm]]
cpu_kind = "performance"
cpus = 8
memory_mb = 16384
